# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-01-14 10:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16, verbose_name='权限名称')),
                ('description', models.TextField(verbose_name='权限秒数')),
            ],
        ),
        migrations.CreateModel(
            name='Vip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16, verbose_name='会员名称')),
                ('level', models.IntegerField(default=0, verbose_name='会员等级')),
                ('duration', models.IntegerField(default=0, verbose_name='购买时常')),
                ('price', models.FloatField(default=0, verbose_name='会员价格')),
            ],
        ),
        migrations.CreateModel(
            name='VipPermRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vip_level', models.IntegerField(verbose_name='会员等级')),
                ('perm_id', models.IntegerField(verbose_name='权限ID')),
            ],
        ),
    ]
