# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-01-08 13:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0002_auto_20210107_1647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='swiped',
            name='stime',
            field=models.DateTimeField(auto_now_add=True, verbose_name='滑动时间'),
        ),
        migrations.AlterField(
            model_name='swiped',
            name='stype',
            field=models.CharField(choices=[('like', '右滑'), ('superlike', '上滑'), ('dislike', '左滑')], max_length=10, verbose_name='滑动类型'),
        ),
    ]
