# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-01-08 13:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0003_auto_20210108_1327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='swiped',
            name='sid',
            field=models.IntegerField(verbose_name='被滑动用户的ID'),
        ),
        migrations.AlterField(
            model_name='swiped',
            name='uid',
            field=models.IntegerField(verbose_name='用户 ID'),
        ),
    ]
