# Generated by Django 3.1.2 on 2020-11-03 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='昵称')),
                ('phone', models.CharField(max_length=20, verbose_name='手机号')),
                ('gender', models.CharField(choices=[('male', '男性'), ('female', '女性')], default='male', max_length=10, verbose_name='性别')),
                ('birthday', models.DateField(default='1990-01-01', verbose_name='生日')),
                ('location', models.CharField(choices=[('北京', '北京'), ('上海', '上海'), ('深圳', '深圳'), ('苏州', '苏州'), ('西安', '西安'), ('武汉', '武汉'), ('沈阳', '武汉')], default='北京', max_length=20, verbose_name='常居地')),
                ('avatar', models.CharField(max_length=256, verbose_name='个人形象的URL')),
            ],
        ),
    ]
