# Generated by Django 3.1.2 on 2020-11-04 01:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_password'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user',
            table='user',
        ),
    ]
