# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-01-14 10:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='Vip_end',
            field=models.DateTimeField(default='2100-01-01', verbose_name='会员过期时间'),
        ),
        migrations.AddField(
            model_name='user',
            name='vip_id',
            field=models.IntegerField(default=1, verbose_name='用户对应的ID'),
        ),
    ]
